### PR TITLE
Masks example notebook

### PR DESCRIPTION
**Pull request by takluyver**
It should now be easy to make masks using the geometry, and you don't need to assemble images to use the mask - e.g. if you want to sum intensity in a given region.

I've put together an example to highlight this.

### CODE REVIEW

**Comment by tmichela** [comment]
One remark on the form: It seems that people use the masks the other way around (mask zones to ignore),
else LGTM

**Comment by takluyver** [comment]
I thought both ways are used in different places? In any case, it's a good
point that we should mention inverting the mask with ~mask.

**Comment by tmichela** [comment]
> I thought both ways are used in different places?

OK, I'm probably biased by the kind of experiment I've seen most

**Comment by takluyver** [comment]
I've added a note about how to get the other kind of mask.

**Comment by tmichela** [comment]
Thansk; LGTM

**Comment by fangohr** [comment]
Thanks - looks great.

**Pull request merged**
