### PR TITLE
Motor tracking for Jungfrau4M

### PR DESCRIPTION
**Pull request by egorsobolev**
%subj%

@takluyver @JamesWrigley

### CODE REVIEW

**Comment by takluyver** [comment]
Like with EXtra#224, I assume you've tried this out and checked that the results make sense? I don't know the details of JF4M, so I'm happy to trust you on the details of how motors & modules are assigned. The code LGTM, not that there's really any new code here. :slightly_smiling_face:

**Comment by egorsobolev** [comment]
I asked all around and did the best what I can. But we will need to check the axis direction and assignment of the motors to the half next time when we will again refine the geometry. I will cross fingers and merge as is for now.

**Review by JamesWrigley — COMMENTED** [review]
I think this should be mentioned somewhere in the documentation, but otherwise LGTM!

(though I am absolutely not an expert on geometry)

**Comment by egorsobolev** [comment]
Thanks, @JamesWrigley

**Comment by JamesWrigley** [comment]
Sorry, I actually meant that the class should be in the RST docs :sweat_smile: But it's not urgent, it can wait till you've verified the constants if you like.

**Comment by egorsobolev** [comment]
Hmm... you are right. Looks like, there is no place for it. I think we need a new section

**Pull request merged**
