### PR TITLE
Add geom.offset() method

### PR DESCRIPTION
**Pull request by takluyver**
Move part or all of the detector by a given amount.

Closes gh-21

### CODE REVIEW

**Comment by takluyver** [comment]
Using this in geoAssembler (see https://github.com/European-XFEL/geoAssembler/pull/24) resulted in code like this:

```python
self.exgeom_obj = (self.exgeom_obj_orig
                   .offset(quad_offsets_m[0], modules=q_slices[1])
                   .offset(quad_offsets_m[1], modules=q_slices[2])
                   .offset(quad_offsets_m[2], modules=q_slices[3])
                   .offset(quad_offsets_m[3], modules=q_slices[4])
                   )
```

I'm thinking about whether & how to make it possible to pass all the offsets to a single method, rather than chaining four calls.

**Comment by takluyver** [comment]
I have refined this so it's possible to specify a separate shift per module. So the above example can now be:

```python
self.exgeom_obj = self.exgeom_obj.offset(
    np.repeat(quad_offsets_m, repeats=4)
)
```

**Comment by tmichela** [comment]
The interface is a bit hard to comprehend I think, as the arguments are interdependent and the shift argument can be applied to all modules, certain module or tiles (each of them can be filter as well). Maybe it is worth adding 1 or 2 examples, or making the doc a bit more explicit?

Else, LGTM!

**Comment by takluyver** [comment]
Good point. I've expanded the docstring now - is that clearer?

**Comment by tmichela** [comment]
Nice, thanks,

LGTM

**Pull request merged**
